name: 01 - Hello World

on:
  push: # Dispara a action em qualquer push
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
