name: 04 - Calcular 2 + 2

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Calcular e mostrar a variável
        run: |
          SOMA=$((2+2))
          echo "O resultado de 2+2 é $SOMA"
